# Generated by Django 4.0.2 on 2022-04-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('company_name', models.CharField(max_length=255, verbose_name='Company')),
                ('company_website', models.URLField(verbose_name='Company Website')),
                ('position', models.CharField(choices=[('jr', 'Junior'), ('sr', 'Senior'), ('as', 'Associate'), ('mgr', 'Manager'), ('ld', 'Lead')], max_length=3)),
                ('employee_status', models.CharField(choices=[('crnt', 'Current Employee'), ('ex', 'Ex Employee')], max_length=4, verbose_name='Employee Status')),
                ('experience', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('10+', '10+')], max_length=3, verbose_name='Years Of Experience')),
                ('gender', models.CharField(choices=[('ml', 'Male'), ('fml', 'Female'), ('othr', 'Other')], max_length=4)),
            ],
        ),
    ]
