# Generated by Django 4.0.2 on 2022-04-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='role',
            field=models.CharField(default='Software Engineer', max_length=255),
            preserve_default=False,
        ),
    ]
