# Generated by Django 4.0.2 on 2022-04-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_salary_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ('-id',)},
        ),
    ]
