# Generated by Django 4.0.2 on 2022-04-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='password',
            field=models.CharField(default='nepalchina', max_length=50, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
