# Generated by Django 4.0.2 on 2022-02-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('work_day', models.IntegerField(default=6)),
                ('type', models.CharField(choices=[('non remote', 'non remote'), ('remote', 'remote')], default='non remote', max_length=20)),
                ('is_paid', models.BooleanField(default=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_benefits', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
