# Generated by Django 4.0.2 on 2022-03-08 16:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('apply_before', models.DateField(blank=True, null=True, verbose_name='apply before')),
                ('education_level', models.CharField(blank=True, max_length=255, null=True, verbose_name='education level')),
                ('no_of_vacancy', models.CharField(blank=True, max_length=255, null=True, verbose_name='number of vacancy')),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('specification', ckeditor.fields.RichTextField(blank=True, verbose_name='job specification')),
                ('requirement', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='technical requirement')),
                ('benefit', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('work_day', models.IntegerField(default=6)),
                ('type', models.CharField(choices=[('non remote', 'non remote'), ('remote', 'remote')], default='non remote', max_length=20)),
                ('is_paid', models.BooleanField(default=True, help_text='for internship only')),
                ('duration', models.CharField(blank=True, help_text='for internship only', max_length=255, null=True)),
                ('additional_benefits', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='job1app.category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
