# Generated by Django 4.0.2 on 2022-02-21 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job1app', '0002_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.CharField(blank=True, help_text='for internship only', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='for internship only'),
        ),
    ]
