# Generated by Django 4.0.2 on 2022-02-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job1app', '0003_job_created_job_slug_job_updated_alter_job_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
