# Generated by Django 4.0.2 on 2022-02-22 14:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job1app', '0005_alter_job_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
