# Generated by Django 4.0.2 on 2022-02-22 14:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job1app', '0006_alter_job_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='content',
        ),
        migrations.AddField(
            model_name='job',
            name='benefit',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirement',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='technical requirement'),
        ),
        migrations.AddField(
            model_name='job',
            name='specification',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='job specification'),
        ),
    ]
