# Generated by Django 4.0.2 on 2022-02-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job1app', '0007_remove_job_content_job_benefit_job_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_before',
            field=models.DateTimeField(blank=True, null=True, verbose_name='apply before'),
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='education level'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='no_of_vacancy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='number of vacancy'),
        ),
    ]
