# Generated by Django 4.0.2 on 2022-02-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job1app', '0008_job_apply_before_job_education_level_job_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_before',
            field=models.DateField(blank=True, null=True, verbose_name='apply before'),
        ),
    ]
